// <auto-generated />
using CodeFirstApproach.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CodeFirstApproach.Migrations
{
    [DbContext(typeof(ItemContext))]
    [Migration("20230612060342_initialmigration")]
    partial class initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeFirstApproach.Models.Items", b =>
                {
                    b.Property<long>("Item_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Item_Id"));

                    b.Property<string>("Item_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Item_Price")
                        .HasColumnType("bigint");

                    b.Property<long>("Item_Quantity")
                        .HasColumnType("bigint");

                    b.Property<int>("Item_SSNCode")
                        .HasColumnType("int");

                    b.Property<int>("Item_Status")
                        .HasColumnType("int");

                    b.HasKey("Item_Id");

                    b.ToTable("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
